# Generated by Django 3.2.9 on 2021-11-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211109_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category-images/category.png', upload_to='category-images'),
        ),
    ]
