# Generated by Django 3.2.9 on 2022-02-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
    ]
