# Generated by Django 3.2.9 on 2021-11-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default='fake id', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
    ]
